### ISSUE TITLE
Bannière

### ISSUE THREAD

**Issue by tdimov93** [Dragomitch/projetphp#1]
Il manque la bannière.

**Comment by Dragomitch** [comment]
Well, you can find there a [https://github.com/Dragomitch/projetphp/blob/master/Projet/views/header.php#L14](Link for the insertion of the banner.) You just have to uncomment :p

**Comment by jy95** [comment]
Why do you comment this line 👎  ? This banner was so ugly for you ?

**Comment by Dragomitch** [comment]
Well @jy95 ... We do what we want on OUR projets. Thx see you.
